--------------------------------------------------------
-- Archivo creado  - lunes-junio-05-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_EMP
--------------------------------------------------------

   CREATE SEQUENCE  "SEMANA14"."SEQ_ID_EMP"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ARRIENDO_CAMION
--------------------------------------------------------

  CREATE TABLE "SEMANA14"."ARRIENDO_CAMION" 
   (	"ID_ARRIENDO" NUMBER(7,0), 
	"NRO_PATENTE" VARCHAR2(6 BYTE), 
	"NUMRUN_CLI" NUMBER(10,0), 
	"FECHA_INI_ARRIENDO" VARCHAR2(6 BYTE), 
	"DIAS_SOLICITADOS" NUMBER(6,0), 
	"FECHA_DEVOLUCION" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Table CAMION
--------------------------------------------------------

  CREATE TABLE "SEMANA14"."CAMION" 
   (	"NRO_PATENTE" VARCHAR2(6 BYTE), 
	"COLOR" VARCHAR2(15 BYTE), 
	"MOTOR" VARCHAR2(5 BYTE), 
	"ANIO" NUMBER(5,0), 
	"VALOR_ARRIENDO_DIA" VARCHAR2(7 BYTE), 
	"VALOR_GARANTIA_DIA" VARCHAR2(6 BYTE), 
	"ID_TIPO_CAMION" VARCHAR2(10 BYTE), 
	"NUMRUN_EMP" NUMBER(10,0), 
	"ID_MARCA" NUMBER, 
	"TIPO_CAMION" VARCHAR2(40 BYTE), 
	"MARCA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "SEMANA14"."CLIENTE" 
   (	"NUMRUN_CLI" NUMBER(10,0), 
	"DVRUN_CLI" VARCHAR2(1 BYTE), 
	"APPATERNO_CLI" VARCHAR2(30 BYTE), 
	"APMATERNO_CLI" VARCHAR2(30 BYTE), 
	"PNOMBRE_CLI" VARCHAR2(30 BYTE), 
	"SNOMBRE_CLI" VARCHAR2(30 BYTE), 
	"DIRECCION" VARCHAR2(60 BYTE), 
	"CELULAR" NUMBER(15,0), 
	"FONO_FIJO_CLI" NUMBER(15,0), 
	"RENTA" VARCHAR2(7 BYTE), 
	"FECHA_NAC_CLI" DATE, 
	"ID_COMUNA" NUMBER(3,0), 
	"ID_TIPO_CLI" VARCHAR2(2 BYTE), 
	"ID_ESTADO_CIVIL" NUMBER(1,0), 
	"TIPO_CLIENTE" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Table COMUNA
--------------------------------------------------------

  CREATE TABLE "SEMANA14"."COMUNA" 
   (	"ID_COMUNA" NUMBER(3,0), 
	"NOMBRE_COMUNA" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Table EMPLEADO
--------------------------------------------------------

  CREATE TABLE "SEMANA14"."EMPLEADO" 
   (	"NUMRUN_EMP" NUMBER(10,0), 
	"DVRUN_EMP" VARCHAR2(1 BYTE), 
	"APPATERNO_EMP" VARCHAR2(30 BYTE), 
	"APMATERNO_EMP" VARCHAR2(30 BYTE), 
	"PNOMBRE_EMP" VARCHAR2(25 BYTE), 
	"SNOMBRE_EMP" VARCHAR2(25 BYTE), 
	"DIRECCION_EMP" VARCHAR2(60 BYTE), 
	"SEXO" CHAR(1 BYTE), 
	"CELULAR_EMP" NUMBER(15,0), 
	"FONO_FIJO_EMP" NUMBER(15,0), 
	"FECHA_NAC" DATE, 
	"FECHA_CONTRATO" DATE, 
	"SUELDO_BASE" NUMBER(7,0), 
	"ID_COMUNA" NUMBER(3,0), 
	"ID_TIPO_SAL" VARCHAR2(3 BYTE), 
	"ID_ESTADO_CIVIL" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Table ESTADO_CIVIL
--------------------------------------------------------

  CREATE TABLE "SEMANA14"."ESTADO_CIVIL" 
   (	"ID_ESTADO_CIVIL" NUMBER(1,0), 
	"ESTADO_CIVIL" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Table TIPO_SALUD
--------------------------------------------------------

  CREATE TABLE "SEMANA14"."TIPO_SALUD" 
   (	"ID_TIPO_SAL" VARCHAR2(3 BYTE), 
	"DESCRIPCION" VARCHAR2(100 BYTE), 
	"PCT_SUELDO" NUMBER(3,1)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSAUX" ;
REM INSERTING into SEMANA14.ARRIENDO_CAMION
SET DEFINE OFF;
REM INSERTING into SEMANA14.CAMION
SET DEFINE OFF;
REM INSERTING into SEMANA14.CLIENTE
SET DEFINE OFF;
REM INSERTING into SEMANA14.COMUNA
SET DEFINE OFF;
REM INSERTING into SEMANA14.EMPLEADO
SET DEFINE OFF;
REM INSERTING into SEMANA14.ESTADO_CIVIL
SET DEFINE OFF;
REM INSERTING into SEMANA14.TIPO_SALUD
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007592
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMANA14"."SYS_C007592" ON "SEMANA14"."ARRIENDO_CAMION" ("ID_ARRIENDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Index SYS_C007603
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMANA14"."SYS_C007603" ON "SEMANA14"."CLIENTE" ("NUMRUN_CLI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Index SYS_C007605
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMANA14"."SYS_C007605" ON "SEMANA14"."COMUNA" ("ID_COMUNA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Index SYS_C007614
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMANA14"."SYS_C007614" ON "SEMANA14"."CAMION" ("NRO_PATENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Index SYS_C007626
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMANA14"."SYS_C007626" ON "SEMANA14"."EMPLEADO" ("NUMRUN_EMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Index SYS_C007630
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMANA14"."SYS_C007630" ON "SEMANA14"."TIPO_SALUD" ("ID_TIPO_SAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Index SYS_C007633
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMANA14"."SYS_C007633" ON "SEMANA14"."ESTADO_CIVIL" ("ID_ESTADO_CIVIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Index SYS_C007592
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMANA14"."SYS_C007592" ON "SEMANA14"."ARRIENDO_CAMION" ("ID_ARRIENDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Index SYS_C007614
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMANA14"."SYS_C007614" ON "SEMANA14"."CAMION" ("NRO_PATENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Index SYS_C007603
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMANA14"."SYS_C007603" ON "SEMANA14"."CLIENTE" ("NUMRUN_CLI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Index SYS_C007605
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMANA14"."SYS_C007605" ON "SEMANA14"."COMUNA" ("ID_COMUNA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Index SYS_C007626
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMANA14"."SYS_C007626" ON "SEMANA14"."EMPLEADO" ("NUMRUN_EMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Index SYS_C007633
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMANA14"."SYS_C007633" ON "SEMANA14"."ESTADO_CIVIL" ("ID_ESTADO_CIVIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Index SYS_C007630
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEMANA14"."SYS_C007630" ON "SEMANA14"."TIPO_SALUD" ("ID_TIPO_SAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  Constraints for Table ARRIENDO_CAMION
--------------------------------------------------------

  ALTER TABLE "SEMANA14"."ARRIENDO_CAMION" MODIFY ("ID_ARRIENDO" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."ARRIENDO_CAMION" MODIFY ("NRO_PATENTE" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."ARRIENDO_CAMION" MODIFY ("NUMRUN_CLI" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."ARRIENDO_CAMION" MODIFY ("FECHA_INI_ARRIENDO" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."ARRIENDO_CAMION" ADD PRIMARY KEY ("ID_ARRIENDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CAMION
--------------------------------------------------------

  ALTER TABLE "SEMANA14"."CAMION" MODIFY ("NRO_PATENTE" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."CAMION" MODIFY ("COLOR" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."CAMION" MODIFY ("MOTOR" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."CAMION" MODIFY ("VALOR_ARRIENDO_DIA" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."CAMION" MODIFY ("ID_TIPO_CAMION" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."CAMION" MODIFY ("ID_MARCA" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."CAMION" MODIFY ("TIPO_CAMION" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."CAMION" MODIFY ("MARCA" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."CAMION" ADD PRIMARY KEY ("NRO_PATENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "SEMANA14"."CLIENTE" MODIFY ("NUMRUN_CLI" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."CLIENTE" MODIFY ("DVRUN_CLI" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."CLIENTE" MODIFY ("APPATERNO_CLI" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."CLIENTE" MODIFY ("APMATERNO_CLI" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."CLIENTE" MODIFY ("PNOMBRE_CLI" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."CLIENTE" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."CLIENTE" MODIFY ("RENTA" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."CLIENTE" MODIFY ("ID_TIPO_CLI" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."CLIENTE" MODIFY ("ID_ESTADO_CIVIL" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."CLIENTE" MODIFY ("TIPO_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."CLIENTE" ADD PRIMARY KEY ("NUMRUN_CLI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMUNA
--------------------------------------------------------

  ALTER TABLE "SEMANA14"."COMUNA" MODIFY ("ID_COMUNA" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."COMUNA" ADD PRIMARY KEY ("ID_COMUNA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "SEMANA14"."EMPLEADO" MODIFY ("NUMRUN_EMP" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."EMPLEADO" MODIFY ("DVRUN_EMP" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."EMPLEADO" MODIFY ("APPATERNO_EMP" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."EMPLEADO" MODIFY ("APMATERNO_EMP" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."EMPLEADO" MODIFY ("PNOMBRE_EMP" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."EMPLEADO" MODIFY ("DIRECCION_EMP" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."EMPLEADO" MODIFY ("SEXO" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."EMPLEADO" MODIFY ("FECHA_NAC" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."EMPLEADO" MODIFY ("SUELDO_BASE" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."EMPLEADO" MODIFY ("ID_TIPO_SAL" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."EMPLEADO" MODIFY ("ID_ESTADO_CIVIL" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."EMPLEADO" ADD PRIMARY KEY ("NUMRUN_EMP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTADO_CIVIL
--------------------------------------------------------

  ALTER TABLE "SEMANA14"."ESTADO_CIVIL" MODIFY ("ID_ESTADO_CIVIL" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."ESTADO_CIVIL" MODIFY ("ESTADO_CIVIL" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."ESTADO_CIVIL" ADD PRIMARY KEY ("ID_ESTADO_CIVIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_SALUD
--------------------------------------------------------

  ALTER TABLE "SEMANA14"."TIPO_SALUD" MODIFY ("ID_TIPO_SAL" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."TIPO_SALUD" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."TIPO_SALUD" MODIFY ("PCT_SUELDO" NOT NULL ENABLE);
  ALTER TABLE "SEMANA14"."TIPO_SALUD" ADD PRIMARY KEY ("ID_TIPO_SAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "SYSAUX"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ARRIENDO_CAMION
--------------------------------------------------------

  ALTER TABLE "SEMANA14"."ARRIENDO_CAMION" ADD CONSTRAINT "ARRIENDO_CAMION_NRO_PATENTE_FK" FOREIGN KEY ("NRO_PATENTE")
	  REFERENCES "SEMANA14"."CAMION" ("NRO_PATENTE") ENABLE;
  ALTER TABLE "SEMANA14"."ARRIENDO_CAMION" ADD CONSTRAINT "ARRIENDO_CAMION_NUMRUN_CLI_FK" FOREIGN KEY ("NUMRUN_CLI")
	  REFERENCES "SEMANA14"."CLIENTE" ("NUMRUN_CLI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CAMION
--------------------------------------------------------

  ALTER TABLE "SEMANA14"."CAMION" ADD CONSTRAINT "CAMION_NUMRUN_EMP_FK" FOREIGN KEY ("NUMRUN_EMP")
	  REFERENCES "SEMANA14"."EMPLEADO" ("NUMRUN_EMP") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "SEMANA14"."CLIENTE" ADD CONSTRAINT "CLIENTE_ID_COMUNA_FK" FOREIGN KEY ("ID_COMUNA")
	  REFERENCES "SEMANA14"."COMUNA" ("ID_COMUNA") ENABLE;
  ALTER TABLE "SEMANA14"."CLIENTE" ADD CONSTRAINT "CLIENTE_ID_ESTADO_CIVIL_FK" FOREIGN KEY ("ID_ESTADO_CIVIL")
	  REFERENCES "SEMANA14"."ESTADO_CIVIL" ("ID_ESTADO_CIVIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "SEMANA14"."EMPLEADO" ADD CONSTRAINT "EMPLEADO_ID_TIPO_SAL_FK" FOREIGN KEY ("ID_TIPO_SAL")
	  REFERENCES "SEMANA14"."TIPO_SALUD" ("ID_TIPO_SAL") ENABLE;
  ALTER TABLE "SEMANA14"."EMPLEADO" ADD CONSTRAINT "EMPLEADO_ID_ESTADO_CIVIL_FK" FOREIGN KEY ("ID_ESTADO_CIVIL")
	  REFERENCES "SEMANA14"."ESTADO_CIVIL" ("ID_ESTADO_CIVIL") ENABLE;
