-- USER SQL
--                  NOMBRE DE USUARIO                   CONTRASEÑA
CREATE    USER      "SEMANA16"          IDENTIFIED BY   "123"
DEFAULT   TABLESPACE "SYSAUX"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "SEMANA16" QUOTA UNLIMITED ON "SYSAUX";

-- ROLES
GRANT "CONNECT" TO "SEMANA16" ;
GRANT "RESOURCE" TO "SEMANA16" ;
